language: python

python: 
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

install:
  - pip install -r requirements.txt

script: 
  - pytest --cov
  - coveralls